apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverperformance-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverperformance-nodejs
  template:
    metadata:
      labels:
        app: serverperformance-nodejs
    spec:
      containers:
        - name: serverperformance-nodejs
          image: jsrankit/serverperformance-nodejs:14-d798ef4-20250408-2201
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: serverperformance-nodejs-service
spec:
  selector:
    app: serverperformance-nodejs
  ports:
    - protocol: TCP
      port: 3000         # Service port (external)
      targetPort: 3000 # Port your app listens on
  type: ClusterIP      # Use LoadBalancer if exposing externally